# Generated by Django 5.1.7 on 2025-06-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_customer_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer_table',
        ),
    ]
