# Generated by Django 5.1.7 on 2025-06-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_options_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelOptions(
            name='cartbill',
            options={'ordering': ['-id'], 'verbose_name': 'cart_bill', 'verbose_name_plural': 'carts_bills'},
        ),
    ]
