# Generated by Django 5.1.7 on 2025-06-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_cart_options_alter_cartbill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='appartment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
