# Generated by Django 5.1.7 on 2025-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('offer', models.IntegerField()),
                ('is_percentage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers  ',
                'db_table': 'customer_offer',
                'ordering': ['-id'],
            },
        ),
    ]
