# Generated by Django 5.1.7 on 2025-06-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_coupon_code_offer_coupen_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbill',
            name='address',
        ),
    ]
