# Generated by Django 5.1.7 on 2025-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_cartbill_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'PL'), ('AC', 'AC'), ('PR', 'PR'), ('DI', 'DI'), ('CA', 'CA')], max_length=255),
        ),
    ]
